<?php
/**
 * @file
 * Mymudoule is a linkit extender example module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function mymodule_ctools_plugin_directory($module, $plugin) {
  if ($module == 'linkit' && !empty($plugin)) {
    return "plugins/" . $plugin;
  }
}

/**
 * Implementation of hook_ctools_plugin_api().
 *
 * Tell CTools that we support the default_mymodule_presets API.
 */
function mymodule_ctools_plugin_api($module, $api) {
  if ($module == 'linkit' && $api == 'linkit_profiles') {
    return array('version' => 1);
  }
}
