<?php
/**
 * @file
 * Main file for Mymodule module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function mymodule_ctools_plugin_directory($module, $plugin) {
  if ($module == 'linkit' && !empty($plugin)) {
    return "plugins/" . $plugin;
  }
}

/**
 * Implements hook_entity_info().
 */
function mymodule_entity_info() {
  return array(
    'mymodule_entity' => array(
      'label' => t('My module entity'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'mymodule_entity',
      'uri callback' => 'entity_class_uri',
      'entity keys' => array(
        'id' => 'id',
        'label' => 'label',
      ),
      // To enable this entity with Linkit you have to specify that.
      'linkit' => TRUE,
    ),
  );
}

/**
 * Implements hook_linkit_plugin_entities_alter().
 *
 * If we want to use our own class for our own entity, we have to alter the
 * plugin handler.
 *
 * BE SURE THAT YOU INCLUDE THE CLASS FILE.
 * Example in mymodule.info
 */
function mymodule_linkit_search_plugin_entities_alter(&$plugins) {

  if (isset($plugins['entity:mymodule_entity'])) {
    $path = drupal_get_path('module', 'mymodule') . '/plugins/linkit_search/';
    $plugins['entity:mymodule_entity']['handler'] = array(
      'class' => 'LinkitPluginMymoduleEntity',
      'file' => 'myplugin-entity.class.php',
      'path' => $path,
    );
  }
}